AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for EC2, S3, Aurora MySQL cluster, S3 VPC Endpoint, and Secrets Manager with automatic VPC creation'

Parameters:
  EC2InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [t3.micro, t3.small, t3.medium, m5.large, m5.xlarge]
    Description: EC2 instance type

Resources:
  # VPC and Networking
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: LogAnalysisVPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: false

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: false

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, MySQL, Streamlit and VSCode
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
          Description: VSCode Server access
      VpcId: !Ref VPC

  # Lambda function to update secrets
  UpdateSecretFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import json

          def handler(event, context):
            if event['RequestType'] in ['Create', 'Update']:
              secret_manager = boto3.client('secretsmanager')
              rds = boto3.client('rds')
              
              secret_id = event['ResourceProperties']['SecretId']
              cluster_id = event['ResourceProperties']['ClusterId']
              
              try:
                response = rds.describe_db_clusters(DBClusterIdentifier=cluster_id)
                endpoint = response['DBClusters'][0]['Endpoint']
                
                secret = secret_manager.get_secret_value(SecretId=secret_id)
                secret_dict = json.loads(secret['SecretString'])
                secret_dict['host'] = endpoint
                
                secret_manager.put_secret_value(
                  SecretId=secret_id,
                  SecretString=json.dumps(secret_dict)
                )
                cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                print(f"Error updating secret: {str(e)}")
                cfnresponse.send(event, context, cfnresponse.FAILED, {})
                return
            else:
              cfnresponse.send(event, context, cfnresponse.SUCCESS, {})

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                  - secretsmanager:ListSecrets
                Resource: 
                  - !Ref AuroraSecret
        - PolicyName: RDSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds:DescribeDBClusters
                Resource: '*'
  # IAM Role for EC2
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles: 
        - !Ref EC2Role

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}'
      InstanceType: !Ref EC2InstanceType
      SecurityGroupIds: 
        - !Ref SecurityGroup
      SubnetId: !Ref PublicSubnet1
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: LogAnalysisInstance
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            apt-get update -y
            apt-get install -y python3-pip python3-dev python3-venv
            
            # Install development tools and MySQL development libraries
            apt-get install -y build-essential libmysqlclient-dev pkg-config
            
            # Install AWS CLI v2
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            apt-get install -y unzip
            unzip awscliv2.zip
            ./aws/install
            
            # Install SSM Agent (usually pre-installed on Ubuntu AMIs)
            snap install amazon-ssm-agent --classic
            systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent.service
            systemctl start snap.amazon-ssm-agent.amazon-ssm-agent.service

            # Install Amazon Kinesis Agent
            wget https://s3.amazonaws.com/kinesis-agent-install-packages/aws-kinesis-agent-latest.deb
            dpkg -i aws-kinesis-agent-latest.deb
            systemctl enable aws-kinesis-agent
            systemctl start aws-kinesis-agent

            # Install Node.js for VSCode Server
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs

            # Set up Python environment and install packages for ubuntu user
            su - ubuntu << EOF
            python3 -m venv myenv
            source myenv/bin/activate
            pip install --upgrade pip
            pip install mysql-connector-python mysql mysql-connector boto3 langchain-aws streamlit

            # Set AWS region
            echo "export AWS_DEFAULT_REGION=${AWS::Region}" >> ~/.bashrc

            # Create data directory
            mkdir ~/data
            mkdir ~/workspace
            EOF

            # Install VSCode Server for ubuntu user
            echo "Installing VSCode Server..."
            sudo -u ubuntu bash -c 'curl -fsSL https://code-server.dev/install.sh | sh'

            # Configure VSCode Server
            mkdir -p /home/ubuntu/.config/code-server
            mkdir -p /home/ubuntu/.local/share/code-server/User/

            # Create VSCode Server config
            cat > /home/ubuntu/.config/code-server/config.yaml << 'EOFVSCODE'
            cert: false
            auth: password
            password: gameloganalysis2024!
            bind-addr: 0.0.0.0:8080
            EOFVSCODE

            # Create VSCode settings
            cat > /home/ubuntu/.local/share/code-server/User/settings.json << 'EOFSETTINGS'
            {
              "extensions.autoUpdate": false,
              "extensions.autoCheckUpdates": false,
              "telemetry.telemetryLevel": "off",
              "security.workspace.trust.startupPrompt": "never",
              "security.workspace.trust.enabled": false,
              "security.workspace.trust.banner": "never",
              "security.workspace.trust.emptyWindow": false,
              "terminal.integrated.defaultProfile.linux": "bash"
            }
            EOFSETTINGS

            # Set proper ownership
            chown -R ubuntu:ubuntu /home/ubuntu/.config
            chown -R ubuntu:ubuntu /home/ubuntu/.local
            chown -R ubuntu:ubuntu /home/ubuntu/workspace

            # Enable and start VSCode Server service
            systemctl enable --now code-server@ubuntu

            # Create password change script
            cat > /home/ubuntu/change-vscode-password.sh << 'EOFSCRIPT'
            #!/bin/bash
            echo "현재 VSCode 서버 비밀번호: gameloganalysis2024!"
            read -s -p "새 비밀번호 입력: " NEW_PASSWORD
            echo ""
            sed -i "s/password: .*/password: $NEW_PASSWORD/" /home/ubuntu/.config/code-server/config.yaml
            sudo systemctl restart code-server@ubuntu
            echo "VSCode 서버 비밀번호가 변경되었습니다."
            EOFSCRIPT

            chmod +x /home/ubuntu/change-vscode-password.sh
            chown ubuntu:ubuntu /home/ubuntu/change-vscode-password.sh

            # Ensure the script has finished
            echo "UserData script has completed." > /tmp/userdata_finished

  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket

  # Aurora MySQL Cluster
  AuroraDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora DB
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  # Secrets Manager Secret
  AuroraSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: gamedb1-cluster
      Description: Secrets for Aurora MySQL Cluster
      SecretString: !Sub '{"username":"dbadmin","password":"12345678","engine":"mysql","host":"gamedb1-cluster.cluster-${AWS::Region}.rds.amazonaws.com","port":3306,"dbClusterIdentifier":"gamedb1-cluster","dbname":"game"}'

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      DatabaseName: game
      DBClusterIdentifier: gamedb1-cluster
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref AuroraSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref AuroraSecret, ':SecretString:password}}' ]]
      DBSubnetGroupName: !Ref AuroraDBSubnetGroup
      VpcSecurityGroupIds: 
        - !Ref SecurityGroup

  AuroraDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBInstanceClass: db.r5.large
      PubliclyAccessible: false
  
  UpdateSecretCustomResource:
    Type: Custom::UpdateSecret
    DependsOn:
      - AuroraDBCluster
    Properties:
      ServiceToken: !GetAtt UpdateSecretFunction.Arn
      SecretId: !Ref AuroraSecret
      ClusterId: !Ref AuroraDBCluster

  # S3 VPC Endpoint
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref VPC
      RouteTableIds:
        - !Ref PublicRouteTable

Outputs:
  EC2InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  EC2PublicIP:
    Description: EC2 Instance Public IP
    Value: !GetAtt EC2Instance.PublicIp

  VSCodeServerURL:
    Description: VSCode Server URL
    Value: !Sub "http://${EC2Instance.PublicIp}:8080"

  VSCodeServerPassword:
    Description: VSCode Server Initial Password
    Value: "gameloganalysis2024!"

  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket

  AuroraClusterEndpoint:
    Description: Aurora Cluster Endpoint
    Value: !GetAtt AuroraDBCluster.Endpoint.Address

  S3VPCEndpointId:
    Description: S3 VPC Endpoint ID
    Value: !Ref S3Endpoint

  AuroraSecretARN:
    Description: ARN of Aurora Secret
    Value: !Ref AuroraSecret

  VpcId:
    Description: VPC ID
    Value: !Ref VPC

  PublicSubnet1:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1

  PublicSubnet2:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2

  PrivateSubnet1:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1

  PrivateSubnet2:
    Description: Private Subnet 2 ID
    Value: !Ref PrivateSubnet2